### ISSUE TITLE
Any chance of uploading the .jar file? 

### ISSUE THREAD

**Issue by roo7break** [tejado/ssoDecrypt#1]
I am having trouble compiling the java file. Any chance you could upload the jar file? or you can email it to roo7break at gmail dot com.

Thanks

Nik

**Comment by tejado** [comment]
I created (right now) a release with a download link to a binary package. 
There is no jar file but you can just run ssoDecrypt.cmd (win) or ssoDecrypt.sh (*nix) which will execute the java class with the correct class path to bouncycastle and oks (both included in the binary package under libs/).

Nevertheless, you have to add the "Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files" to your java installation. Can be found [here](http://www.oracle.com/technetwork/java/javase/downloads/index.html)

Can you try it out and give me a short feedback?
What problems have you encountered during compiling?
