### ISSUE TITLE
I can't find oks

### ISSUE THREAD

**Issue by djrodriguezp** [tejado/ssoDecrypt#2]
Hello,

The site to download oks is down and i can't find the class on internet. Do you have any copy of the oks jar?

Best Regards,

**Comment by tejado** [comment]
Hi,

thanks for the hint. I added the libs to the repo with the latest commit: https://github.com/tejado/ssoDecrypt/commit/488bce4a1305b63ca5749744d7fee1aef7526d5d

Regards!

**Comment by tejado** [comment]
Addtional question: are you interessted in further support, e.g. 12c?

**Comment by djrodriguezp** [comment]
Thank you very much for your support.
